FROM debian:12.12

ENV container docker

STOPSIGNAL SIGRTMIN+3

RUN apt-get update -y && \
    apt-get install -y \
    systemd \
    systemd-sysv \
    dbus && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

VOLUME ["/sys/fs/cgroup"]

CMD ["/sbin/init"]
