FROM debian:12.12

ENV container docker  
STOPSIGNAL SIGRTMIN+3

RUN apt-get update && \
    apt-get install -y systemd systemd-sysv dbus rsync && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

VOLUME [ "/sys/fs/cgroup" ]

RUN mkdir -p /tmp && chmod 1777 /tmp

CMD ["/sbin/init"]